name: "CI environment setup"
description: |
  * set home bazelrc for CI runner
  * set buildbuddy api key
  * setup vendored external deps

inputs:
  buildbuddy-api-key:
    required: true
    description: |
      BuildBuddy API key to access the remote cache.
  external-cache-key:
    default: ${{ runner.os }}-default
    description: |
      Key specifying which cache to restore.

runs:
  using: "composite"
  steps:
    - uses: nixbuild/nix-quick-install-action@v32

    - name: setup ci bazelrc
      shell: bash
      run: |
        cp .github/workflows/ci.bazelrc ~/.bazelrc
        echo 'build:remote-cache --remote_header=x-buildbuddy-api-key=${{ inputs.buildbuddy-api-key }}' >> ~/.bazelrc

    - name: setup bazel vendored external deps
      shell: bash
      run: |
        echo "common --vendor_dir=$HOME/bazel_external_deps" >> ~/.bazelrc

    - name: restore bazel vendored external deps
      uses: nix-community/cache-nix-action/restore@v6
      with:
        paths: |
          ~/bazel_external_deps
          /nix
          ~/.cache/nix
          ~root/.cache/nix
        primary-key: bazel-external-cache-${{ inputs.external-cache-key }}
        save: false
